# -*- coding: utf-8 -*-
"""ML-MAJOR-JUNE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10dwvRdis75WXxlnoVCy0CkbgkSxypUJP
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score,confusion_matrix

from sklearn.svm import SVC

from sklearn.preprocessing import StandardScaler

df = pd.read_csv("E:/Internships/ML_internship(smartknowers)/data/diabetes.csv")

x = df.iloc[:, 0:8].values
y = df.iloc[:, 8].values

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2, random_state=0)

# SS = StandardScaler()

# x_train = SS.fit_transform(x_train)
# x_test = SS.fit_transform(x_test)

x_train

Model = SVC(random_state=0, kernel='linear')

Model.fit(x_train, y_train)

y_pred = Model.predict(x_test)

print(y_pred)

print(y_test)

print(accuracy_score(y_test,y_pred))

print(confusion_matrix(y_test,y_pred))
